#commion
keep-alive-time: 10 #s
secret: coderxiaoc812728

#connection
enable-long-connection: false
connection-timeout: 30 #s

#limit
enable-limit: false
limit-buffer-size: 1024 #kb

#server
main-port: 12345
conn-chan-count: 2000

#client
server-ip: 127.0.0.1
connections:
  - local-port: 8090
    local-host: 127.0.0.1
    task-port: 0
    web-port: 0
    secret: coderxiaoc812728
  - local-port: 8091
    task-port: 0
    web-port: 0
    secret: coderxiaoc812728
  - local-port: 3000
    task-port: 0
    web-port: 0
    secret: coderxiaoc812728
